### ISSUE TITLE
Suggestion to add amazon leadership principles

### ISSUE THREAD

**Issue by dalawwa** [andrmoel/tech-lead-collection#2]
Please have a look at https://www.amazon.jobs/content/en/our-workplace/leadership-principles

Maybe it's worth a mention somewhere. Please ignore and close otherwise

**Comment by andrmoel** [comment]
Please open a PR :D

**Comment by dalawwa** [comment]
Denied :D
![image](https://user-images.githubusercontent.com/7680079/222809820-6544a49a-472b-4904-880d-ae119105eee1.png)

**Comment by andrmoel** [comment]
Will add
